import type { DevPipelineEdgeCondition, DevPipelineNodeParams, DevPipelineStepKind } from './types'

export type PipelineTemplateCategory = 'frontend' | 'backend' | 'deploy' | 'cloud' | 'utility' | 'demo'

export type PipelineTemplatePlatform = 'cross' | 'windows' | 'linux'

export type PipelineNodeTemplate = {
  id: string
  category: PipelineTemplateCategory
  labelKey: string
  descriptionKey: string
  tags: string[]
  iconKey: string
  accentColor: string
  stepKind: DevPipelineStepKind
  command?: string
  scriptPath?: string
  cwd?: string
  waitForExit?: boolean
  params?: DevPipelineNodeParams
  approvalMessage?: string
  platform?: PipelineTemplatePlatform
}

export type PipelineSnippetNode = {
  templateNodeId: string
  labelKey: string
  iconKey: string
  accentColor: string
  stepKind: DevPipelineStepKind
  command?: string
  scriptPath?: string
  cwd?: string
  waitForExit?: boolean
  params?: DevPipelineNodeParams
  approvalMessage?: string
  relativePosition: { x: number; y: number }
}

export type PipelineSnippetEdge = {
  source: string
  target: string
  condition?: DevPipelineEdgeCondition
  label?: string
}

export type PipelineSnippetTemplate = {
  id: string
  category: PipelineTemplateCategory
  labelKey: string
  descriptionKey: string
  tags: string[]
  nodes: PipelineSnippetNode[]
  edges: PipelineSnippetEdge[]
}

export const PIPELINE_NODE_TEMPLATES: PipelineNodeTemplate[] = [
  // ── Frontend ──────────────────────────────────────────────────────────────
  {
    id: 'fe-angular-install',
    category: 'frontend',
    labelKey: 'feAngularInstallLabel',
    descriptionKey: 'feAngularInstallDesc',
    tags: ['angular', 'npm', 'install'],
    iconKey: 'Globe',
    accentColor: '#38bdf8',
    stepKind: 'shell',
    command: 'npm ci',
    waitForExit: true,
  },
  {
    id: 'fe-angular-lint',
    category: 'frontend',
    labelKey: 'feAngularLintLabel',
    descriptionKey: 'feAngularLintDesc',
    tags: ['angular', 'lint'],
    iconKey: 'CheckCircle2',
    accentColor: '#38bdf8',
    stepKind: 'shell',
    command: 'ng lint',
    waitForExit: true,
  },
  {
    id: 'fe-angular-test',
    category: 'frontend',
    labelKey: 'feAngularTestLabel',
    descriptionKey: 'feAngularTestDesc',
    tags: ['angular', 'test'],
    iconKey: 'CheckCircle2',
    accentColor: '#38bdf8',
    stepKind: 'shell',
    command: 'ng test --watch=false --browsers=ChromeHeadless',
    waitForExit: true,
  },
  {
    id: 'fe-angular-build',
    category: 'frontend',
    labelKey: 'feAngularBuildLabel',
    descriptionKey: 'feAngularBuildDesc',
    tags: ['angular', 'build', 'production'],
    iconKey: 'Package',
    accentColor: '#38bdf8',
    stepKind: 'shell',
    command: 'ng build --configuration production',
    waitForExit: true,
  },
  {
    id: 'fe-pnpm-install',
    category: 'frontend',
    labelKey: 'feInstallLabel',
    descriptionKey: 'feInstallDesc',
    tags: ['pnpm', 'npm', 'install', 'frontend'],
    iconKey: 'Globe',
    accentColor: '#38bdf8',
    stepKind: 'shell',
    command: 'pnpm install --frozen-lockfile',
    waitForExit: true,
  },
  {
    id: 'fe-build',
    category: 'frontend',
    labelKey: 'feBuildLabel',
    descriptionKey: 'feBuildDesc',
    tags: ['build', 'frontend', 'vite', 'react', 'vue'],
    iconKey: 'Package',
    accentColor: '#38bdf8',
    stepKind: 'shell',
    command: 'pnpm run build',
    waitForExit: true,
  },
  {
    id: 'fe-eslint',
    category: 'frontend',
    labelKey: 'feEslintLabel',
    descriptionKey: 'feEslintDesc',
    tags: ['eslint', 'lint'],
    iconKey: 'CheckCircle2',
    accentColor: '#38bdf8',
    stepKind: 'shell',
    command: 'npx eslint . --ext .ts,.tsx,.js,.jsx',
    waitForExit: true,
  },
  {
    id: 'fe-jest',
    category: 'frontend',
    labelKey: 'feJestLabel',
    descriptionKey: 'feJestDesc',
    tags: ['jest', 'test', 'unit'],
    iconKey: 'CheckCircle2',
    accentColor: '#38bdf8',
    stepKind: 'shell',
    command: 'npx jest --ci',
    waitForExit: true,
  },
  {
    id: 'fe-dev-server',
    category: 'frontend',
    labelKey: 'feDevServerLabel',
    descriptionKey: 'feDevServerDesc',
    tags: ['dev', 'serve', 'preview', 'watch'],
    iconKey: 'Eye',
    accentColor: '#38bdf8',
    stepKind: 'shell',
    command: 'pnpm run dev',
    waitForExit: false,
  },
  {
    id: 'fe-prettier',
    category: 'frontend',
    labelKey: 'fePrettierLabel',
    descriptionKey: 'fePrettierDesc',
    tags: ['prettier', 'format', 'lint'],
    iconKey: 'CheckCircle2',
    accentColor: '#38bdf8',
    stepKind: 'shell',
    command: 'pnpm prettier --check .',
    waitForExit: true,
  },
  {
    id: 'fe-typecheck',
    category: 'frontend',
    labelKey: 'feTypecheckLabel',
    descriptionKey: 'feTypecheckDesc',
    tags: ['typescript', 'tsc', 'typecheck'],
    iconKey: 'CheckCircle2',
    accentColor: '#38bdf8',
    stepKind: 'shell',
    command: 'pnpm tsc --noEmit',
    waitForExit: true,
  },

  // ── Backend ───────────────────────────────────────────────────────────────
  {
    id: 'be-maven-package',
    category: 'backend',
    labelKey: 'beMavenPackageLabel',
    descriptionKey: 'beMavenPackageDesc',
    tags: ['maven', 'java', 'package'],
    iconKey: 'Cpu',
    accentColor: '#a78bfa',
    stepKind: 'shell',
    command: 'mvn -B clean package -DskipTests',
    waitForExit: true,
  },
  {
    id: 'be-maven-verify',
    category: 'backend',
    labelKey: 'beMavenVerifyLabel',
    descriptionKey: 'beMavenVerifyDesc',
    tags: ['maven', 'java', 'verify', 'test'],
    iconKey: 'CheckCircle2',
    accentColor: '#a78bfa',
    stepKind: 'shell',
    command: 'mvn -B verify',
    waitForExit: true,
  },
  {
    id: 'be-gradle-build',
    category: 'backend',
    labelKey: 'beGradleBuildLabel',
    descriptionKey: 'beGradleBuildDesc',
    tags: ['gradle', 'java', 'build'],
    iconKey: 'Cpu',
    accentColor: '#a78bfa',
    stepKind: 'shell',
    command: './gradlew clean build',
    waitForExit: true,
  },
  {
    id: 'be-dotnet-restore',
    category: 'backend',
    labelKey: 'beDotnetRestoreLabel',
    descriptionKey: 'beDotnetRestoreDesc',
    tags: ['dotnet', 'restore', 'nuget'],
    iconKey: 'Cpu',
    accentColor: '#a78bfa',
    stepKind: 'shell',
    command: 'dotnet restore',
    waitForExit: true,
  },
  {
    id: 'be-dotnet-build',
    category: 'backend',
    labelKey: 'beDotnetBuildLabel',
    descriptionKey: 'beDotnetBuildDesc',
    tags: ['dotnet', 'build', 'release'],
    iconKey: 'Package',
    accentColor: '#a78bfa',
    stepKind: 'shell',
    command: 'dotnet build -c Release',
    waitForExit: true,
  },
  {
    id: 'be-dotnet-test',
    category: 'backend',
    labelKey: 'beDotnetTestLabel',
    descriptionKey: 'beDotnetTestDesc',
    tags: ['dotnet', 'test'],
    iconKey: 'CheckCircle2',
    accentColor: '#a78bfa',
    stepKind: 'shell',
    command: 'dotnet test --no-build -c Release',
    waitForExit: true,
  },
  {
    id: 'be-dotnet-publish',
    category: 'backend',
    labelKey: 'beDotnetPublishLabel',
    descriptionKey: 'beDotnetPublishDesc',
    tags: ['dotnet', 'publish', 'release'],
    iconKey: 'Package',
    accentColor: '#a78bfa',
    stepKind: 'shell',
    command: 'dotnet publish -c Release -o ./publish',
    waitForExit: true,
  },
  {
    id: 'be-maven-install',
    category: 'backend',
    labelKey: 'beMavenInstallLabel',
    descriptionKey: 'beMavenInstallDesc',
    tags: ['maven', 'java', 'install'],
    iconKey: 'Cpu',
    accentColor: '#a78bfa',
    stepKind: 'shell',
    command: 'mvn -B clean install',
    waitForExit: true,
  },

  // ── Deploy ────────────────────────────────────────────────────────────────
  {
    id: 'dep-docker-build',
    category: 'deploy',
    labelKey: 'depDockerBuildLabel',
    descriptionKey: 'depDockerBuildDesc',
    tags: ['docker', 'build', 'image'],
    iconKey: 'Layers',
    accentColor: '#4ade80',
    stepKind: 'shell',
    command: 'docker build -t $IMAGE_NAME:$TAG .',
    waitForExit: true,
  },
  {
    id: 'dep-docker-push',
    category: 'deploy',
    labelKey: 'depDockerPushLabel',
    descriptionKey: 'depDockerPushDesc',
    tags: ['docker', 'push', 'registry'],
    iconKey: 'Layers',
    accentColor: '#4ade80',
    stepKind: 'shell',
    command: 'docker push $IMAGE_NAME:$TAG',
    waitForExit: true,
  },
  {
    id: 'dep-aws-s3-sync',
    category: 'deploy',
    labelKey: 'depAwsS3SyncLabel',
    descriptionKey: 'depAwsS3SyncDesc',
    tags: ['aws', 's3', 'sync', 'deploy'],
    iconKey: 'Database',
    accentColor: '#4ade80',
    stepKind: 'shell',
    command: 'aws s3 sync ./dist s3://$S3_BUCKET --delete',
    waitForExit: true,
  },
  {
    id: 'dep-aws-ecs-update',
    category: 'deploy',
    labelKey: 'depAwsEcsUpdateLabel',
    descriptionKey: 'depAwsEcsUpdateDesc',
    tags: ['aws', 'ecs', 'deploy'],
    iconKey: 'Package',
    accentColor: '#4ade80',
    stepKind: 'shell',
    command: 'aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment',
    waitForExit: true,
  },
  {
    id: 'dep-aws-lambda',
    category: 'deploy',
    labelKey: 'depAwsLambdaLabel',
    descriptionKey: 'depAwsLambdaDesc',
    tags: ['aws', 'lambda', 'deploy'],
    iconKey: 'Zap',
    accentColor: '#4ade80',
    stepKind: 'shell',
    command: 'aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://function.zip',
    waitForExit: true,
  },
  {
    id: 'dep-tomcat-war',
    category: 'deploy',
    labelKey: 'depTomcatWarLabel',
    descriptionKey: 'depTomcatWarDesc',
    tags: ['tomcat', 'war', 'java', 'deploy'],
    iconKey: 'Package',
    accentColor: '#4ade80',
    stepKind: 'shell',
    command: 'cp target/*.war $TOMCAT_WEBAPPS/',
    waitForExit: true,
  },
  {
    id: 'dep-k8s-apply',
    category: 'deploy',
    labelKey: 'depK8sApplyLabel',
    descriptionKey: 'depK8sApplyDesc',
    tags: ['kubernetes', 'k8s', 'deploy'],
    iconKey: 'Layers',
    accentColor: '#4ade80',
    stepKind: 'shell',
    command: 'kubectl apply -f k8s/',
    waitForExit: true,
  },
  {
    id: 'dep-ssh-deploy',
    category: 'deploy',
    labelKey: 'depSshDeployLabel',
    descriptionKey: 'depSshDeployDesc',
    tags: ['ssh', 'deploy', 'remote'],
    iconKey: 'Lock',
    accentColor: '#4ade80',
    stepKind: 'shell',
    command: 'ssh $DEPLOY_USER@$DEPLOY_HOST "cd $APP_DIR && git pull && npm install && pm2 restart all"',
    waitForExit: true,
  },
  {
    id: 'dep-iis-deploy',
    category: 'deploy',
    labelKey: 'depIisDeployLabel',
    descriptionKey: 'depIisDeployDesc',
    tags: ['iis', 'windows', 'deploy'],
    iconKey: 'Globe',
    accentColor: '#4ade80',
    stepKind: 'shell',
    command: 'xcopy /E /I /Y .\\publish %IIS_APP_PATH%',
    waitForExit: true,
    platform: 'windows',
  },
  {
    id: 'dep-firebase-hosting',
    category: 'deploy',
    labelKey: 'depFirebaseLabel',
    descriptionKey: 'depFirebaseDesc',
    tags: ['firebase', 'hosting', 'deploy'],
    iconKey: 'Globe',
    accentColor: '#4ade80',
    stepKind: 'shell',
    command: 'firebase deploy --only hosting',
    waitForExit: true,
  },
  {
    id: 'dep-vercel',
    category: 'deploy',
    labelKey: 'depVercelLabel',
    descriptionKey: 'depVercelDesc',
    tags: ['vercel', 'deploy', 'frontend'],
    iconKey: 'Globe',
    accentColor: '#4ade80',
    stepKind: 'shell',
    command: 'vercel --prod',
    waitForExit: true,
  },

  // ── Cloud ─────────────────────────────────────────────────────────────────
  {
    id: 'cloud-ecr-push',
    category: 'cloud',
    labelKey: 'cloudEcrPushLabel',
    descriptionKey: 'cloudEcrPushDesc',
    tags: ['aws', 'ecr', 'docker', 'push'],
    iconKey: 'Database',
    accentColor: '#22d3ee',
    stepKind: 'shell',
    command: 'aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY && docker push $ECR_REGISTRY/$IMAGE_NAME:$TAG',
    waitForExit: true,
  },
  {
    id: 'cloud-aws-codedeploy',
    category: 'cloud',
    labelKey: 'cloudAwsCodedeployLabel',
    descriptionKey: 'cloudAwsCodedeployDesc',
    tags: ['aws', 'codedeploy', 'deploy'],
    iconKey: 'Package',
    accentColor: '#22d3ee',
    stepKind: 'shell',
    command: 'aws deploy create-deployment --application-name $APP_NAME --deployment-group-name $DEPLOY_GROUP --s3-location bucket=$S3_BUCKET,key=$S3_KEY,bundleType=zip',
    waitForExit: true,
  },
  {
    id: 'cloud-docker-compose',
    category: 'cloud',
    labelKey: 'cloudDockerComposeLabel',
    descriptionKey: 'cloudDockerComposeDesc',
    tags: ['docker-compose', 'deploy'],
    iconKey: 'Layers',
    accentColor: '#22d3ee',
    stepKind: 'shell',
    command: 'docker compose pull && docker compose up -d --remove-orphans',
    waitForExit: true,
  },
  {
    id: 'cloud-firebase-emulator',
    category: 'cloud',
    labelKey: 'cloudFirebaseEmulatorLabel',
    descriptionKey: 'cloudFirebaseEmulatorDesc',
    tags: ['firebase', 'emulator', 'local'],
    iconKey: 'Eye',
    accentColor: '#22d3ee',
    stepKind: 'shell',
    command: 'firebase emulators:start',
    waitForExit: false,
  },

  // ── Utility ───────────────────────────────────────────────────────────────
  {
    id: 'util-approval',
    category: 'utility',
    labelKey: 'utilApprovalLabel',
    descriptionKey: 'utilApprovalDesc',
    tags: ['approval', 'manual', 'gate'],
    iconKey: 'ShieldCheck',
    accentColor: '#facc15',
    stepKind: 'approval',
    approvalMessage: 'Approve to continue the pipeline?',
  },
  {
    id: 'util-http-check',
    category: 'utility',
    labelKey: 'utilHttpCheckLabel',
    descriptionKey: 'utilHttpCheckDesc',
    tags: ['http', 'health', 'webhook', 'curl'],
    iconKey: 'Activity',
    accentColor: '#facc15',
    stepKind: 'http-check',
    params: { url: 'http://localhost:3000/health', expectedStatus: 200, timeoutMs: 30000, retryDelayMs: 2000, maxRetries: 10 },
  },
  {
    id: 'util-delay',
    category: 'utility',
    labelKey: 'utilDelayLabel',
    descriptionKey: 'utilDelayDesc',
    tags: ['delay', 'wait', 'retry'],
    iconKey: 'Clock',
    accentColor: '#facc15',
    stepKind: 'delay',
    params: { ms: 5000 },
  },
  {
    id: 'util-git-pull',
    category: 'utility',
    labelKey: 'utilGitPullLabel',
    descriptionKey: 'utilGitPullDesc',
    tags: ['git', 'pull', 'scm'],
    iconKey: 'GitBranch',
    accentColor: '#facc15',
    stepKind: 'shell',
    command: 'git pull',
    waitForExit: true,
  },
  {
    id: 'util-git-tag',
    category: 'utility',
    labelKey: 'utilGitTagLabel',
    descriptionKey: 'utilGitTagDesc',
    tags: ['git', 'tag', 'release'],
    iconKey: 'GitBranch',
    accentColor: '#facc15',
    stepKind: 'shell',
    command: 'git tag -a $TAG -m "$TAG" && git push origin $TAG',
    waitForExit: true,
  },
  {
    id: 'util-notify',
    category: 'utility',
    labelKey: 'utilNotifyLabel',
    descriptionKey: 'utilNotifyDesc',
    tags: ['slack', 'teams', 'notify', 'webhook'],
    iconKey: 'Bell',
    accentColor: '#facc15',
    stepKind: 'shell',
    command: "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Pipeline finished\"}' $WEBHOOK_URL",
    waitForExit: true,
  },
  {
    id: 'util-echo-marker',
    category: 'utility',
    labelKey: 'utilEchoMarkerLabel',
    descriptionKey: 'utilEchoMarkerDesc',
    tags: ['echo', 'marker', 'log'],
    iconKey: 'Bell',
    accentColor: '#facc15',
    stepKind: 'shell',
    command: 'echo "=== PIPELINE MARKER ==="',
    waitForExit: true,
  },
  {
    id: 'util-env-check',
    category: 'utility',
    labelKey: 'utilEnvCheckLabel',
    descriptionKey: 'utilEnvCheckDesc',
    tags: ['env', 'check', 'validate'],
    iconKey: 'AlertCircle',
    accentColor: '#facc15',
    stepKind: 'shell',
    command: 'node -e "const r=[\'NODE_ENV\'];const m=r.filter(k=>!process.env[k]);if(m.length){console.error(\'Missing: \'+m.join(\', \'));process.exit(1)}"',
    waitForExit: true,
  },
  {
    id: 'util-cleanup',
    category: 'utility',
    labelKey: 'utilCleanupLabel',
    descriptionKey: 'utilCleanupDesc',
    tags: ['cleanup', 'rimraf', 'docker', 'prune'],
    iconKey: 'Layers',
    accentColor: '#facc15',
    stepKind: 'shell',
    command: 'npx rimraf dist',
    waitForExit: true,
  },
  {
    id: 'util-blank-shell',
    category: 'utility',
    labelKey: 'utilBlankShellLabel',
    descriptionKey: 'utilBlankShellDesc',
    tags: ['blank', 'shell', 'custom'],
    iconKey: 'Zap',
    accentColor: '#facc15',
    stepKind: 'shell',
    command: '',
    waitForExit: true,
  },

  // ── Demo ──────────────────────────────────────────────────────────────────
  {
    id: 'demo-noop',
    category: 'demo',
    labelKey: 'demoNoopLabel',
    descriptionKey: 'demoNoopDesc',
    tags: ['demo', 'noop'],
    iconKey: 'Play',
    accentColor: '#94a3b8',
    stepKind: 'noop',
  },
]

export const PIPELINE_SNIPPET_TEMPLATES: PipelineSnippetTemplate[] = [
  {
    id: 'recipe-angular-s3',
    category: 'frontend',
    labelKey: 'recipeAngularS3Label',
    descriptionKey: 'recipeAngularS3Desc',
    tags: ['angular', 'aws', 's3'],
    nodes: [
      { templateNodeId: 'n1', labelKey: 'feAngularInstallLabel', iconKey: 'Globe', accentColor: '#38bdf8', stepKind: 'shell', command: 'npm ci', waitForExit: true, relativePosition: { x: 0, y: 0 } },
      { templateNodeId: 'n2', labelKey: 'feAngularLintLabel', iconKey: 'CheckCircle2', accentColor: '#38bdf8', stepKind: 'shell', command: 'ng lint', waitForExit: true, relativePosition: { x: 0, y: 120 } },
      { templateNodeId: 'n3', labelKey: 'feAngularBuildLabel', iconKey: 'Package', accentColor: '#38bdf8', stepKind: 'shell', command: 'ng build --configuration production', waitForExit: true, relativePosition: { x: 0, y: 240 } },
      { templateNodeId: 'n4', labelKey: 'depAwsS3SyncLabel', iconKey: 'Database', accentColor: '#4ade80', stepKind: 'shell', command: 'aws s3 sync ./dist s3://$S3_BUCKET --delete', waitForExit: true, relativePosition: { x: 0, y: 360 } },
    ],
    edges: [
      { source: 'n1', target: 'n2' },
      { source: 'n2', target: 'n3' },
      { source: 'n3', target: 'n4' },
    ],
  },
  {
    id: 'recipe-angular-tomcat',
    category: 'frontend',
    labelKey: 'recipeAngularTomcatLabel',
    descriptionKey: 'recipeAngularTomcatDesc',
    tags: ['angular', 'tomcat', 'java'],
    nodes: [
      { templateNodeId: 'n1', labelKey: 'feAngularInstallLabel', iconKey: 'Globe', accentColor: '#38bdf8', stepKind: 'shell', command: 'npm ci', waitForExit: true, relativePosition: { x: 0, y: 0 } },
      { templateNodeId: 'n2', labelKey: 'feAngularBuildLabel', iconKey: 'Package', accentColor: '#38bdf8', stepKind: 'shell', command: 'ng build --configuration production', waitForExit: true, relativePosition: { x: 0, y: 120 } },
      { templateNodeId: 'n3', labelKey: 'depTomcatWarLabel', iconKey: 'Package', accentColor: '#4ade80', stepKind: 'shell', command: 'cp target/*.war $TOMCAT_WEBAPPS/', waitForExit: true, relativePosition: { x: 0, y: 240 } },
    ],
    edges: [
      { source: 'n1', target: 'n2' },
      { source: 'n2', target: 'n3' },
    ],
  },
  {
    id: 'recipe-java-tomcat',
    category: 'backend',
    labelKey: 'recipeJavaTomcatLabel',
    descriptionKey: 'recipeJavaTomcatDesc',
    tags: ['java', 'maven', 'tomcat'],
    nodes: [
      { templateNodeId: 'n1', labelKey: 'beMavenPackageLabel', iconKey: 'Cpu', accentColor: '#a78bfa', stepKind: 'shell', command: 'mvn -B clean package -DskipTests', waitForExit: true, relativePosition: { x: 0, y: 0 } },
      { templateNodeId: 'n2', labelKey: 'depTomcatWarLabel', iconKey: 'Package', accentColor: '#4ade80', stepKind: 'shell', command: 'cp target/*.war $TOMCAT_WEBAPPS/', waitForExit: true, relativePosition: { x: 0, y: 120 } },
    ],
    edges: [
      { source: 'n1', target: 'n2' },
    ],
  },
  {
    id: 'recipe-react-s3',
    category: 'frontend',
    labelKey: 'recipeReactS3Label',
    descriptionKey: 'recipeReactS3Desc',
    tags: ['react', 'aws', 's3'],
    nodes: [
      { templateNodeId: 'n1', labelKey: 'feInstallLabel', iconKey: 'Globe', accentColor: '#38bdf8', stepKind: 'shell', command: 'pnpm install --frozen-lockfile', waitForExit: true, relativePosition: { x: 0, y: 0 } },
      { templateNodeId: 'n2', labelKey: 'feBuildLabel', iconKey: 'Package', accentColor: '#38bdf8', stepKind: 'shell', command: 'pnpm run build', waitForExit: true, relativePosition: { x: 0, y: 120 } },
      { templateNodeId: 'n3', labelKey: 'depAwsS3SyncLabel', iconKey: 'Database', accentColor: '#4ade80', stepKind: 'shell', command: 'aws s3 sync ./dist s3://$S3_BUCKET --delete', waitForExit: true, relativePosition: { x: 0, y: 240 } },
    ],
    edges: [
      { source: 'n1', target: 'n2' },
      { source: 'n2', target: 'n3' },
    ],
  },
  {
    id: 'recipe-dotnet-iis',
    category: 'backend',
    labelKey: 'recipeDotnetIisLabel',
    descriptionKey: 'recipeDotnetIisDesc',
    tags: ['dotnet', 'iis', 'windows'],
    nodes: [
      { templateNodeId: 'n1', labelKey: 'beDotnetRestoreLabel', iconKey: 'Cpu', accentColor: '#a78bfa', stepKind: 'shell', command: 'dotnet restore', waitForExit: true, relativePosition: { x: 0, y: 0 } },
      { templateNodeId: 'n2', labelKey: 'beDotnetBuildLabel', iconKey: 'Package', accentColor: '#a78bfa', stepKind: 'shell', command: 'dotnet build -c Release', waitForExit: true, relativePosition: { x: 0, y: 120 } },
      { templateNodeId: 'n3', labelKey: 'beDotnetPublishLabel', iconKey: 'Package', accentColor: '#a78bfa', stepKind: 'shell', command: 'dotnet publish -c Release -o ./publish', waitForExit: true, relativePosition: { x: 0, y: 240 } },
      { templateNodeId: 'n4', labelKey: 'depIisDeployLabel', iconKey: 'Globe', accentColor: '#4ade80', stepKind: 'shell', command: 'xcopy /E /I /Y .\\publish %IIS_APP_PATH%', waitForExit: true, relativePosition: { x: 0, y: 360 } },
    ],
    edges: [
      { source: 'n1', target: 'n2' },
      { source: 'n2', target: 'n3' },
      { source: 'n3', target: 'n4' },
    ],
  },
  {
    id: 'recipe-docker-ecs',
    category: 'deploy',
    labelKey: 'recipeDockerEcsLabel',
    descriptionKey: 'recipeDockerEcsDesc',
    tags: ['docker', 'ecr', 'ecs', 'aws'],
    nodes: [
      { templateNodeId: 'n1', labelKey: 'depDockerBuildLabel', iconKey: 'Layers', accentColor: '#4ade80', stepKind: 'shell', command: 'docker build -t $IMAGE_NAME:$TAG .', waitForExit: true, relativePosition: { x: 0, y: 0 } },
      { templateNodeId: 'n2', labelKey: 'cloudEcrPushLabel', iconKey: 'Database', accentColor: '#22d3ee', stepKind: 'shell', command: 'aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY && docker push $ECR_REGISTRY/$IMAGE_NAME:$TAG', waitForExit: true, relativePosition: { x: 0, y: 120 } },
      { templateNodeId: 'n3', labelKey: 'depAwsEcsUpdateLabel', iconKey: 'Package', accentColor: '#4ade80', stepKind: 'shell', command: 'aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment', waitForExit: true, relativePosition: { x: 0, y: 240 } },
    ],
    edges: [
      { source: 'n1', target: 'n2' },
      { source: 'n2', target: 'n3' },
    ],
  },
  {
    id: 'recipe-vite-firebase',
    category: 'frontend',
    labelKey: 'recipeViteFirebaseLabel',
    descriptionKey: 'recipeViteFirebaseDesc',
    tags: ['vite', 'firebase', 'hosting'],
    nodes: [
      { templateNodeId: 'n1', labelKey: 'fePnpmInstallLabel', iconKey: 'Globe', accentColor: '#38bdf8', stepKind: 'shell', command: 'pnpm install --frozen-lockfile', waitForExit: true, relativePosition: { x: 0, y: 0 } },
      { templateNodeId: 'n2', labelKey: 'feBuildLabel', iconKey: 'Package', accentColor: '#38bdf8', stepKind: 'shell', command: 'pnpm run build', waitForExit: true, relativePosition: { x: 0, y: 120 } },
      { templateNodeId: 'n3', labelKey: 'depFirebaseHostingLabel', iconKey: 'Globe', accentColor: '#4ade80', stepKind: 'shell', command: 'firebase deploy --only hosting', waitForExit: true, relativePosition: { x: 0, y: 240 } },
    ],
    edges: [
      { source: 'n1', target: 'n2' },
      { source: 'n2', target: 'n3' },
    ],
  },
  {
    id: 'recipe-react-vercel',
    category: 'frontend',
    labelKey: 'recipeReactVercelLabel',
    descriptionKey: 'recipeReactVercelDesc',
    tags: ['react', 'vercel', 'deploy'],
    nodes: [
      { templateNodeId: 'n1', labelKey: 'feInstallLabel', iconKey: 'Globe', accentColor: '#38bdf8', stepKind: 'shell', command: 'pnpm install --frozen-lockfile', waitForExit: true, relativePosition: { x: 0, y: 0 } },
      { templateNodeId: 'n2', labelKey: 'feBuildLabel', iconKey: 'Package', accentColor: '#38bdf8', stepKind: 'shell', command: 'pnpm run build', waitForExit: true, relativePosition: { x: 0, y: 120 } },
      { templateNodeId: 'n3', labelKey: 'depVercelLabel', iconKey: 'Globe', accentColor: '#4ade80', stepKind: 'shell', command: 'vercel --prod', waitForExit: true, relativePosition: { x: 0, y: 240 } },
    ],
    edges: [
      { source: 'n1', target: 'n2' },
      { source: 'n2', target: 'n3' },
    ],
  },
  {
    id: 'recipe-git-notify',
    category: 'utility',
    labelKey: 'recipeGitNotifyLabel',
    descriptionKey: 'recipeGitNotifyDesc',
    tags: ['git', 'slack', 'notify'],
    nodes: [
      { templateNodeId: 'n1', labelKey: 'utilGitPullLabel', iconKey: 'GitBranch', accentColor: '#facc15', stepKind: 'shell', command: 'git pull', waitForExit: true, relativePosition: { x: 0, y: 0 } },
      { templateNodeId: 'n2', labelKey: 'utilBlankShellLabel', iconKey: 'Zap', accentColor: '#facc15', stepKind: 'shell', command: '', waitForExit: true, relativePosition: { x: 0, y: 120 } },
      { templateNodeId: 'n3', labelKey: 'utilNotifyLabel', iconKey: 'Bell', accentColor: '#facc15', stepKind: 'shell', command: "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Pipeline finished\"}' $WEBHOOK_URL", waitForExit: true, relativePosition: { x: 0, y: 240 } },
    ],
    edges: [
      { source: 'n1', target: 'n2' },
      { source: 'n2', target: 'n3' },
    ],
  },
  // ── Flow pattern recipes (conditional branch, parallel, fan-in) ─────────
  {
    id: 'recipe-fail-branch-notify',
    category: 'demo',
    labelKey: 'recipeFailBranchLabel',
    descriptionKey: 'recipeFailBranchDesc',
    tags: ['pattern', 'branch', 'failure', 'notify', 'conditional'],
    nodes: [
      {
        templateNodeId: 'n1',
        labelKey: 'patternBuildStepLabel',
        iconKey: 'Package',
        accentColor: '#38bdf8',
        stepKind: 'shell',
        command: 'pnpm run build',
        waitForExit: true,
        relativePosition: { x: 220, y: 0 },
      },
      {
        templateNodeId: 'n2',
        labelKey: 'patternDeployOkLabel',
        iconKey: 'Rocket',
        accentColor: '#4ade80',
        stepKind: 'shell',
        command: 'vercel --prod',
        waitForExit: true,
        relativePosition: { x: 0, y: 180 },
      },
      {
        templateNodeId: 'n3',
        labelKey: 'patternAlertFailLabel',
        iconKey: 'Bell',
        accentColor: '#f87171',
        stepKind: 'shell',
        command:
          "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Build failed — check pipeline logs\"}' $SLACK_WEBHOOK_URL",
        waitForExit: true,
        relativePosition: { x: 440, y: 180 },
      },
    ],
    edges: [
      { source: 'n1', target: 'n2', condition: 'on-success', label: 'OK' },
      { source: 'n1', target: 'n3', condition: 'on-failure', label: 'fail' },
    ],
  },
  {
    id: 'recipe-parallel-quality-gates',
    category: 'demo',
    labelKey: 'recipeParallelGatesLabel',
    descriptionKey: 'recipeParallelGatesDesc',
    tags: ['pattern', 'parallel', 'lint', 'test', 'fan-in'],
    nodes: [
      {
        templateNodeId: 'n0',
        labelKey: 'utilGitPullLabel',
        iconKey: 'GitBranch',
        accentColor: '#facc15',
        stepKind: 'shell',
        command: 'git pull',
        waitForExit: true,
        relativePosition: { x: 220, y: 0 },
      },
      {
        templateNodeId: 'n1',
        labelKey: 'feEslintLabel',
        iconKey: 'CheckCircle2',
        accentColor: '#38bdf8',
        stepKind: 'shell',
        command: 'pnpm eslint .',
        waitForExit: true,
        relativePosition: { x: 0, y: 140 },
      },
      {
        templateNodeId: 'n2',
        labelKey: 'feJestLabel',
        iconKey: 'CheckCircle2',
        accentColor: '#38bdf8',
        stepKind: 'shell',
        command: 'pnpm jest --ci',
        waitForExit: true,
        relativePosition: { x: 440, y: 140 },
      },
      {
        templateNodeId: 'n3',
        labelKey: 'patternMergeBuildLabel',
        iconKey: 'Package',
        accentColor: '#38bdf8',
        stepKind: 'shell',
        command: 'pnpm run build',
        waitForExit: true,
        relativePosition: { x: 220, y: 300 },
      },
      {
        templateNodeId: 'n4',
        labelKey: 'utilEchoMarkerLabel',
        iconKey: 'CheckCircle2',
        accentColor: '#4ade80',
        stepKind: 'shell',
        command: 'echo === Quality gates passed ===',
        waitForExit: true,
        relativePosition: { x: 220, y: 440 },
      },
    ],
    edges: [
      { source: 'n0', target: 'n1' },
      { source: 'n0', target: 'n2' },
      { source: 'n1', target: 'n3', label: 'lint' },
      { source: 'n2', target: 'n3', label: 'test' },
      { source: 'n3', target: 'n4' },
    ],
  },
  {
    id: 'recipe-parallel-deploy-fanin',
    category: 'demo',
    labelKey: 'recipeParallelDeployLabel',
    descriptionKey: 'recipeParallelDeployDesc',
    tags: ['pattern', 'parallel', 'deploy', 'health', 'fan-in'],
    nodes: [
      {
        templateNodeId: 'n1',
        labelKey: 'patternBuildStepLabel',
        iconKey: 'Package',
        accentColor: '#38bdf8',
        stepKind: 'shell',
        command: 'pnpm run build',
        waitForExit: true,
        relativePosition: { x: 220, y: 0 },
      },
      {
        templateNodeId: 'n2',
        labelKey: 'patternStagingDeployLabel',
        iconKey: 'Globe',
        accentColor: '#4ade80',
        stepKind: 'shell',
        command: 'firebase deploy --only hosting --project $FIREBASE_STAGING',
        waitForExit: true,
        relativePosition: { x: 0, y: 160 },
      },
      {
        templateNodeId: 'n3',
        labelKey: 'utilHttpCheckLabel',
        iconKey: 'Activity',
        accentColor: '#facc15',
        stepKind: 'http-check',
        params: { url: 'http://localhost:3000/health', expectedStatus: 200, timeoutMs: 30000, retryDelayMs: 2000, maxRetries: 10 },
        relativePosition: { x: 440, y: 160 },
      },
      {
        templateNodeId: 'n4',
        labelKey: 'patternPromoteProdLabel',
        iconKey: 'Rocket',
        accentColor: '#4ade80',
        stepKind: 'shell',
        command: 'firebase deploy --only hosting --project $FIREBASE_PROD',
        waitForExit: true,
        relativePosition: { x: 220, y: 320 },
      },
      {
        templateNodeId: 'n5',
        labelKey: 'utilNotifyLabel',
        iconKey: 'Bell',
        accentColor: '#facc15',
        stepKind: 'shell',
        command:
          "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Production deploy complete\"}' $WEBHOOK_URL",
        waitForExit: true,
        relativePosition: { x: 220, y: 460 },
      },
    ],
    edges: [
      { source: 'n1', target: 'n2', label: 'staging' },
      { source: 'n1', target: 'n3', label: 'health' },
      { source: 'n2', target: 'n4', label: 'deployed' },
      { source: 'n3', target: 'n4', label: 'healthy' },
      { source: 'n4', target: 'n5' },
    ],
  },
]

export const PIPELINE_TEMPLATE_CATEGORIES: PipelineTemplateCategory[] = ['frontend', 'backend', 'deploy', 'cloud', 'utility', 'demo']

export function findNodeTemplate(id: string): PipelineNodeTemplate | undefined {
  return PIPELINE_NODE_TEMPLATES.find(t => t.id === id)
}

export function findSnippetTemplate(id: string): PipelineSnippetTemplate | undefined {
  return PIPELINE_SNIPPET_TEMPLATES.find(s => s.id === id)
}
