/**
 * `icon`: tên Lucide (vd. `sunrise`) hoặc ảnh tĩnh: `img:` + đường dẫn public (vd. `img:/achievements/first_login.png`).
 * File ảnh đặt trong `src/resources/public/achievements/`.
 */
export interface AchievementDefinition {
  code: string
  category: 'task' | 'git' | 'review' | 'report' | 'quality' | 'streak' | 'negative'
  tier: 'bronze' | 'silver' | 'gold' | 'special' | 'negative'
  name: string
  description: string
  icon: string
  xp_reward: number
  is_repeatable: boolean
  condition_type: string
  condition_threshold: number | null
  is_negative: boolean
  sort_order: number
}

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  // ─── Welcome ───
  {
    code: 'first_login',
    category: 'task',
    tier: 'bronze',
    name: 'Welcome!',
    description: 'Đăng nhập lần đầu tiên. Chào mừng bạn đến với team!',
    icon: 'img:/achievements/first_login.png',
    xp_reward: 10,
    is_repeatable: false,
    condition_type: 'first_login',
    condition_threshold: null,
    is_negative: false,
    sort_order: 1,
  },
  // ─── Task ───
  {
    code: 'task_first',
    category: 'task',
    tier: 'bronze',
    name: 'First Blood',
    description: 'Hoàn thành task đầu tiên.',
    icon: 'img:/achievements/first_blood.png',
    xp_reward: 20,
    is_repeatable: false,
    condition_type: 'total_tasks_done',
    condition_threshold: 1,
    is_negative: false,
    sort_order: 10,
  },
  {
    code: 'task_10',
    category: 'task',
    tier: 'bronze',
    name: 'Task Crusher',
    description: 'Hoàn thành 10 tasks.',
    icon: 'img:/achievements/task_crusher.png',
    xp_reward: 30,
    is_repeatable: false,
    condition_type: 'total_tasks_done',
    condition_threshold: 10,
    is_negative: false,
    sort_order: 11,
  },
  {
    code: 'task_50',
    category: 'task',
    tier: 'silver',
    name: 'Half Centurion',
    description: 'Hoàn thành 50 tasks.',
    icon: 'shield',
    xp_reward: 60,
    is_repeatable: false,
    condition_type: 'total_tasks_done',
    condition_threshold: 50,
    is_negative: false,
    sort_order: 12,
  },
  {
    code: 'task_100',
    category: 'task',
    tier: 'gold',
    name: 'Centurion',
    description: 'Hoàn thành 100 tasks.',
    icon: 'crown',
    xp_reward: 120,
    is_repeatable: false,
    condition_type: 'total_tasks_done',
    condition_threshold: 100,
    is_negative: false,
    sort_order: 13,
  },
  {
    code: 'task_on_time',
    category: 'task',
    tier: 'bronze',
    name: 'On Time',
    description: 'Hoàn thành task trước hoặc đúng deadline.',
    icon: 'img:/achievements/on_time.png',
    xp_reward: 15,
    is_repeatable: true,
    condition_type: 'total_tasks_on_time',
    condition_threshold: 1,
    is_negative: false,
    sort_order: 14,
  },
  {
    code: 'task_early_bird',
    category: 'task',
    tier: 'silver',
    name: 'Early Bird',
    description: 'Hoàn thành task sớm hơn deadline 3+ ngày.',
    icon: 'sunrise',
    xp_reward: 30,
    is_repeatable: true,
    condition_type: 'total_tasks_early',
    condition_threshold: 1,
    is_negative: false,
    sort_order: 15,
  },
  {
    code: 'task_bug_hunter_10',
    category: 'task',
    tier: 'bronze',
    name: 'Bug Hunter',
    description: 'Hoàn thành 10 bug tasks.',
    icon: 'bug',
    xp_reward: 30,
    is_repeatable: false,
    condition_type: 'total_tasks_bug_done',
    condition_threshold: 10,
    is_negative: false,
    sort_order: 16,
  },
  {
    code: 'task_bug_hunter_50',
    category: 'task',
    tier: 'gold',
    name: 'Exterminator',
    description: 'Hoàn thành 50 bug tasks.',
    icon: 'bug-off',
    xp_reward: 80,
    is_repeatable: false,
    condition_type: 'total_tasks_bug_done',
    condition_threshold: 50,
    is_negative: false,
    sort_order: 17,
  },
  {
    code: 'task_feature_10',
    category: 'task',
    tier: 'silver',
    name: 'Feature Maker',
    description: 'Hoàn thành 10 feature tasks.',
    icon: 'sparkles',
    xp_reward: 40,
    is_repeatable: false,
    condition_type: 'total_tasks_feature_done',
    condition_threshold: 10,
    is_negative: false,
    sort_order: 18,
  },
  {
    code: 'task_creator_50',
    category: 'task',
    tier: 'silver',
    name: 'Architect',
    description: 'Tạo 50 tasks.',
    icon: 'drafting-compass',
    xp_reward: 50,
    is_repeatable: false,
    condition_type: 'total_tasks_created',
    condition_threshold: 50,
    is_negative: false,
    sort_order: 19,
  },
  {
    code: 'task_critical_5',
    category: 'task',
    tier: 'gold',
    name: 'Crisis Manager',
    description: 'Hoàn thành 5 tasks ưu tiên Critical.',
    icon: 'alert-triangle',
    xp_reward: 60,
    is_repeatable: false,
    condition_type: 'total_tasks_critical_done',
    condition_threshold: 5,
    is_negative: false,
    sort_order: 20,
  },
  {
    code: 'task_200',
    category: 'task',
    tier: 'gold',
    name: 'Double Centurion',
    description: 'Hoàn thành 200 tasks.',
    icon: 'trophy',
    xp_reward: 180,
    is_repeatable: false,
    condition_type: 'total_tasks_done',
    condition_threshold: 200,
    is_negative: false,
    sort_order: 21,
  },
  {
    code: 'task_500',
    category: 'task',
    tier: 'special',
    name: 'Legendary Worker',
    description: 'Hoàn thành 500 tasks.',
    icon: 'gem',
    xp_reward: 300,
    is_repeatable: false,
    condition_type: 'total_tasks_done',
    condition_threshold: 500,
    is_negative: false,
    sort_order: 22,
  },
  {
    code: 'task_feature_25',
    category: 'task',
    tier: 'gold',
    name: 'Feature Architect',
    description: 'Hoàn thành 25 feature tasks.',
    icon: 'sparkles',
    xp_reward: 80,
    is_repeatable: false,
    condition_type: 'total_tasks_feature_done',
    condition_threshold: 25,
    is_negative: false,
    sort_order: 23,
  },
  {
    code: 'task_creator_100',
    category: 'task',
    tier: 'gold',
    name: 'Task Master',
    description: 'Tạo 100 tasks.',
    icon: 'drafting-compass',
    xp_reward: 100,
    is_repeatable: false,
    condition_type: 'total_tasks_created',
    condition_threshold: 100,
    is_negative: false,
    sort_order: 24,
  },
  {
    code: 'task_on_time_10',
    category: 'task',
    tier: 'silver',
    name: 'Punctual Pro',
    description: 'Hoàn thành 10 tasks đúng hạn.',
    icon: 'clock',
    xp_reward: 40,
    is_repeatable: false,
    condition_type: 'total_tasks_on_time',
    condition_threshold: 10,
    is_negative: false,
    sort_order: 25,
  },
  {
    code: 'task_early_5',
    category: 'task',
    tier: 'gold',
    name: 'Speed Demon',
    description: 'Hoàn thành 5 tasks sớm hơn deadline 3+ ngày.',
    icon: 'sunrise',
    xp_reward: 50,
    is_repeatable: false,
    condition_type: 'total_tasks_early',
    condition_threshold: 5,
    is_negative: false,
    sort_order: 26,
  },

  // ─── Git ───
  {
    code: 'git_first_commit',
    category: 'git',
    tier: 'bronze',
    name: 'First Commit',
    description: 'Thực hiện commit đầu tiên qua app.',
    icon: 'git-commit',
    xp_reward: 20,
    is_repeatable: false,
    condition_type: 'total_commits',
    condition_threshold: 1,
    is_negative: false,
    sort_order: 30,
  },
  {
    code: 'git_commits_50',
    category: 'git',
    tier: 'bronze',
    name: 'Regular Dev',
    description: 'Thực hiện 50 commits.',
    icon: 'git-commit',
    xp_reward: 40,
    is_repeatable: false,
    condition_type: 'total_commits',
    condition_threshold: 50,
    is_negative: false,
    sort_order: 31,
  },
  {
    code: 'git_commits_200',
    category: 'git',
    tier: 'silver',
    name: 'Committed',
    description: 'Thực hiện 200 commits.',
    icon: 'git-commit',
    xp_reward: 80,
    is_repeatable: false,
    condition_type: 'total_commits',
    condition_threshold: 200,
    is_negative: false,
    sort_order: 32,
  },
  {
    code: 'git_commits_500',
    category: 'git',
    tier: 'silver',
    name: 'Pro Committer',
    description: 'Thực hiện 500 commits.',
    icon: 'git-commit',
    xp_reward: 100,
    is_repeatable: false,
    condition_type: 'total_commits',
    condition_threshold: 500,
    is_negative: false,
    sort_order: 33,
  },
  {
    code: 'git_commits_1000',
    category: 'git',
    tier: 'gold',
    name: 'Code Machine',
    description: 'Thực hiện 1000 commits.',
    icon: 'server',
    xp_reward: 150,
    is_repeatable: false,
    condition_type: 'total_commits',
    condition_threshold: 1000,
    is_negative: false,
    sort_order: 34,
  },
  {
    code: 'git_push_10',
    category: 'git',
    tier: 'bronze',
    name: 'Sender',
    description: 'Push thành công 10 lần.',
    icon: 'upload',
    xp_reward: 20,
    is_repeatable: false,
    condition_type: 'total_pushes',
    condition_threshold: 10,
    is_negative: false,
    sort_order: 35,
  },
  {
    code: 'git_push_100',
    category: 'git',
    tier: 'silver',
    name: 'Deployer',
    description: 'Push thành công 100 lần.',
    icon: 'send',
    xp_reward: 60,
    is_repeatable: false,
    condition_type: 'total_pushes',
    condition_threshold: 100,
    is_negative: false,
    sort_order: 36,
  },
  {
    code: 'git_push_500',
    category: 'git',
    tier: 'gold',
    name: 'Deployment Pro',
    description: 'Push thành công 500 lần.',
    icon: 'send',
    xp_reward: 120,
    is_repeatable: false,
    condition_type: 'total_pushes',
    condition_threshold: 500,
    is_negative: false,
    sort_order: 37,
  },
  {
    code: 'git_branch_5',
    category: 'git',
    tier: 'bronze',
    name: 'Branch Explorer',
    description: 'Tạo 5 branches.',
    icon: 'git-branch',
    xp_reward: 25,
    is_repeatable: false,
    condition_type: 'total_branches_created',
    condition_threshold: 5,
    is_negative: false,
    sort_order: 38,
  },
  {
    code: 'git_branch_10',
    category: 'git',
    tier: 'silver',
    name: 'Branch Master',
    description: 'Tạo 10 branches.',
    icon: 'git-branch',
    xp_reward: 50,
    is_repeatable: false,
    condition_type: 'total_branches_created',
    condition_threshold: 10,
    is_negative: false,
    sort_order: 39,
  },
  {
    code: 'git_merge_10',
    category: 'git',
    tier: 'silver',
    name: 'Merge Master',
    description: 'Merge 10 branches.',
    icon: 'git-merge',
    xp_reward: 50,
    is_repeatable: false,
    condition_type: 'total_merges',
    condition_threshold: 10,
    is_negative: false,
    sort_order: 40,
  },
  {
    code: 'git_merge_25',
    category: 'git',
    tier: 'gold',
    name: 'Merge Ninja',
    description: 'Merge 25 branches.',
    icon: 'git-merge',
    xp_reward: 80,
    is_repeatable: false,
    condition_type: 'total_merges',
    condition_threshold: 25,
    is_negative: false,
    sort_order: 41,
  },
  {
    code: 'git_stash_5',
    category: 'git',
    tier: 'bronze',
    name: 'Safety Net',
    description: 'Dùng stash 5 lần.',
    icon: 'archive',
    xp_reward: 20,
    is_repeatable: false,
    condition_type: 'total_stashes',
    condition_threshold: 5,
    is_negative: false,
    sort_order: 42,
  },
  {
    code: 'git_stash_10',
    category: 'git',
    tier: 'silver',
    name: 'Stash Pro',
    description: 'Dùng stash 10 lần.',
    icon: 'archive',
    xp_reward: 35,
    is_repeatable: false,
    condition_type: 'total_stashes',
    condition_threshold: 10,
    is_negative: false,
    sort_order: 43,
  },
  {
    code: 'git_rebase_10',
    category: 'git',
    tier: 'silver',
    name: 'History Rewriter',
    description: 'Pull với rebase 10 lần.',
    icon: 'history',
    xp_reward: 40,
    is_repeatable: false,
    condition_type: 'total_rebases',
    condition_threshold: 10,
    is_negative: false,
    sort_order: 44,
  },
  {
    code: 'git_rebase_25',
    category: 'git',
    tier: 'gold',
    name: 'Rebase Expert',
    description: 'Pull với rebase 25 lần.',
    icon: 'history',
    xp_reward: 70,
    is_repeatable: false,
    condition_type: 'total_rebases',
    condition_threshold: 25,
    is_negative: false,
    sort_order: 45,
  },
  {
    code: 'git_files_small',
    category: 'git',
    tier: 'bronze',
    name: 'Surgical',
    description: 'Commit với 3 files trở xuống.',
    icon: 'scissors',
    xp_reward: 5,
    is_repeatable: true,
    condition_type: 'commit_files_le3',
    condition_threshold: null,
    is_negative: false,
    sort_order: 46,
  },
  {
    code: 'git_files_bulk',
    category: 'git',
    tier: 'bronze',
    name: 'Bulk Worker',
    description: 'Commit với 16-30 files.',
    icon: 'layers',
    xp_reward: 8,
    is_repeatable: true,
    condition_type: 'commit_files_16_30',
    condition_threshold: null,
    is_negative: false,
    sort_order: 47,
  },
  {
    code: 'git_files_massive',
    category: 'git',
    tier: 'silver',
    name: 'Big Bang',
    description: 'Commit với hơn 50 files.',
    icon: 'package',
    xp_reward: 15,
    is_repeatable: true,
    condition_type: 'commit_files_gt50',
    condition_threshold: null,
    is_negative: false,
    sort_order: 48,
  },
  {
    code: 'git_files_giant_100',
    category: 'git',
    tier: 'special',
    name: 'File Tsunami',
    description: 'Commit một lần với 100 files trở lên.',
    icon: 'waves',
    xp_reward: 30,
    is_repeatable: true,
    condition_type: 'commit_files_ge100',
    condition_threshold: null,
    is_negative: false,
    sort_order: 49,
  },
  {
    code: 'git_insertions_1000',
    category: 'git',
    tier: 'silver',
    name: 'Line Writer',
    description: 'Tổng số dòng thêm vào vượt 1000.',
    icon: 'pen-line',
    xp_reward: 60,
    is_repeatable: false,
    condition_type: 'total_insertions',
    condition_threshold: 1000,
    is_negative: false,
    sort_order: 50,
  },
  {
    code: 'git_insertions_5000',
    category: 'git',
    tier: 'gold',
    name: 'Code Writer',
    description: 'Tổng số dòng thêm vào vượt 5000.',
    icon: 'pen-line',
    xp_reward: 100,
    is_repeatable: false,
    condition_type: 'total_insertions',
    condition_threshold: 5000,
    is_negative: false,
    sort_order: 51,
  },
  {
    code: 'git_insertions_10000',
    category: 'git',
    tier: 'special',
    name: 'Prolific Coder',
    description: 'Tổng số dòng thêm vào vượt 10000.',
    icon: 'file-code',
    xp_reward: 180,
    is_repeatable: false,
    condition_type: 'total_insertions',
    condition_threshold: 10000,
    is_negative: false,
    sort_order: 52,
  },
  {
    code: 'git_streak_7',
    category: 'streak',
    tier: 'silver',
    name: 'Week Warrior',
    description: 'Commit mỗi ngày liên tục 7 ngày.',
    icon: 'flame',
    xp_reward: 70,
    is_repeatable: false,
    condition_type: 'commit_streak_7',
    condition_threshold: 7,
    is_negative: false,
    sort_order: 53,
  },
  {
    code: 'git_streak_14',
    category: 'streak',
    tier: 'silver',
    name: 'Fortnight Fighter',
    description: 'Commit mỗi ngày liên tục 14 ngày.',
    icon: 'flame',
    xp_reward: 100,
    is_repeatable: false,
    condition_type: 'commit_streak_14',
    condition_threshold: 14,
    is_negative: false,
    sort_order: 54,
  },
  {
    code: 'git_streak_30',
    category: 'streak',
    tier: 'gold',
    name: 'Month Dev',
    description: 'Commit mỗi ngày liên tục 30 ngày.',
    icon: 'calendar-check',
    xp_reward: 200,
    is_repeatable: false,
    condition_type: 'commit_streak_30',
    condition_threshold: 30,
    is_negative: false,
    sort_order: 55,
  },
  {
    code: 'git_streak_60',
    category: 'streak',
    tier: 'special',
    name: 'Quarter Dev',
    description: 'Commit mỗi ngày liên tục 60 ngày.',
    icon: 'flame',
    xp_reward: 350,
    is_repeatable: false,
    condition_type: 'commit_streak_60',
    condition_threshold: 60,
    is_negative: false,
    sort_order: 56,
  },

  // ─── Review ───
  {
    code: 'review_first',
    category: 'review',
    tier: 'bronze',
    name: 'First Look',
    description: 'Review commit đầu tiên.',
    icon: 'eye',
    xp_reward: 20,
    is_repeatable: false,
    condition_type: 'total_reviews',
    condition_threshold: 1,
    is_negative: false,
    sort_order: 60,
  },
  {
    code: 'review_25',
    category: 'review',
    tier: 'bronze',
    name: 'Code Reviewer',
    description: 'Review 25 commits.',
    icon: 'search-check',
    xp_reward: 40,
    is_repeatable: false,
    condition_type: 'total_reviews',
    condition_threshold: 25,
    is_negative: false,
    sort_order: 61,
  },
  {
    code: 'review_100',
    category: 'review',
    tier: 'silver',
    name: 'Quality Guardian',
    description: 'Review 100 commits.',
    icon: 'shield-check',
    xp_reward: 80,
    is_repeatable: false,
    condition_type: 'total_reviews',
    condition_threshold: 100,
    is_negative: false,
    sort_order: 62,
  },
  {
    code: 'review_500',
    category: 'review',
    tier: 'gold',
    name: 'Code Oracle',
    description: 'Review 500 commits.',
    icon: 'telescope',
    xp_reward: 200,
    is_repeatable: false,
    condition_type: 'total_reviews',
    condition_threshold: 500,
    is_negative: false,
    sort_order: 63,
  },
  {
    code: 'review_250',
    category: 'review',
    tier: 'gold',
    name: 'Review Champion',
    description: 'Review 250 commits.',
    icon: 'shield-check',
    xp_reward: 120,
    is_repeatable: false,
    condition_type: 'total_reviews',
    condition_threshold: 250,
    is_negative: false,
    sort_order: 64,
  },
  {
    code: 'review_1000',
    category: 'review',
    tier: 'special',
    name: 'Review Legend',
    description: 'Review 1000 commits.',
    icon: 'telescope',
    xp_reward: 300,
    is_repeatable: false,
    condition_type: 'total_reviews',
    condition_threshold: 1000,
    is_negative: false,
    sort_order: 65,
  },

  // ─── Daily Report ───
  {
    code: 'report_first',
    category: 'report',
    tier: 'bronze',
    name: 'First Report',
    description: 'Gửi daily report đầu tiên.',
    icon: 'file-text',
    xp_reward: 15,
    is_repeatable: false,
    condition_type: 'total_reports',
    condition_threshold: 1,
    is_negative: false,
    sort_order: 70,
  },
  {
    code: 'report_streak_7',
    category: 'report',
    tier: 'bronze',
    name: 'Reporter',
    description: 'Gửi daily report 7 ngày liên tiếp.',
    icon: 'calendar-days',
    xp_reward: 40,
    is_repeatable: false,
    condition_type: 'report_streak_7',
    condition_threshold: 7,
    is_negative: false,
    sort_order: 71,
  },
  {
    code: 'report_streak_14',
    category: 'report',
    tier: 'silver',
    name: 'Two Week Reporter',
    description: 'Gửi daily report 14 ngày liên tiếp.',
    icon: 'calendar-days',
    xp_reward: 60,
    is_repeatable: false,
    condition_type: 'report_streak_14',
    condition_threshold: 14,
    is_negative: false,
    sort_order: 72,
  },
  {
    code: 'report_streak_30',
    category: 'report',
    tier: 'silver',
    name: 'Consistent',
    description: 'Gửi daily report 30 ngày liên tiếp.',
    icon: 'calendar-check-2',
    xp_reward: 100,
    is_repeatable: false,
    condition_type: 'report_streak_30',
    condition_threshold: 30,
    is_negative: false,
    sort_order: 73,
  },
  {
    code: 'report_50',
    category: 'report',
    tier: 'silver',
    name: 'Diligent Reporter',
    description: 'Gửi tổng cộng 50 daily reports.',
    icon: 'file-text',
    xp_reward: 60,
    is_repeatable: false,
    condition_type: 'total_reports',
    condition_threshold: 50,
    is_negative: false,
    sort_order: 74,
  },
  {
    code: 'report_100',
    category: 'report',
    tier: 'gold',
    name: 'Historian',
    description: 'Gửi tổng cộng 100 daily reports.',
    icon: 'book-open',
    xp_reward: 120,
    is_repeatable: false,
    condition_type: 'total_reports',
    condition_threshold: 100,
    is_negative: false,
    sort_order: 75,
  },
  {
    code: 'report_200',
    category: 'report',
    tier: 'special',
    name: 'Report Master',
    description: 'Gửi tổng cộng 200 daily reports.',
    icon: 'book-marked',
    xp_reward: 180,
    is_repeatable: false,
    condition_type: 'total_reports',
    condition_threshold: 200,
    is_negative: false,
    sort_order: 76,
  },

  // ─── Quality / SpotBugs ───
  {
    code: 'spotbugs_clean_10',
    category: 'quality',
    tier: 'bronze',
    name: 'Zero Defect',
    description: 'Chạy SpotBugs 10 lần không có lỗi nào.',
    icon: 'check-circle',
    xp_reward: 50,
    is_repeatable: false,
    condition_type: 'total_spotbugs_clean',
    condition_threshold: 10,
    is_negative: false,
    sort_order: 80,
  },
  {
    code: 'spotbugs_clean_50',
    category: 'quality',
    tier: 'gold',
    name: 'Flawless',
    description: 'Chạy SpotBugs 50 lần không có lỗi nào.',
    icon: 'badge-check',
    xp_reward: 150,
    is_repeatable: false,
    condition_type: 'total_spotbugs_clean',
    condition_threshold: 50,
    is_negative: false,
    sort_order: 82,
  },
  {
    code: 'spotbugs_clean_25',
    category: 'quality',
    tier: 'silver',
    name: 'Quality Keeper',
    description: 'Chạy SpotBugs 25 lần không có lỗi nào.',
    icon: 'check-circle',
    xp_reward: 80,
    is_repeatable: false,
    condition_type: 'total_spotbugs_clean',
    condition_threshold: 25,
    is_negative: false,
    sort_order: 81,
  },
  {
    code: 'spotbugs_clean_100',
    category: 'quality',
    tier: 'special',
    name: 'Code Perfectionist',
    description: 'Chạy SpotBugs 100 lần không có lỗi nào.',
    icon: 'shield-plus',
    xp_reward: 250,
    is_repeatable: false,
    condition_type: 'total_spotbugs_clean',
    condition_threshold: 100,
    is_negative: false,
    sort_order: 83,
  },
  {
    code: 'coding_rule_5',
    category: 'quality',
    tier: 'silver',
    name: 'Rule Maker',
    description: 'Tạo 5 coding rules.',
    icon: 'scroll-text',
    xp_reward: 60,
    is_repeatable: false,
    condition_type: 'total_coding_rules_created',
    condition_threshold: 5,
    is_negative: false,
    sort_order: 84,
  },
  {
    code: 'coding_rule_10',
    category: 'quality',
    tier: 'gold',
    name: 'Rule Architect',
    description: 'Tạo 10 coding rules.',
    icon: 'scroll-text',
    xp_reward: 100,
    is_repeatable: false,
    condition_type: 'total_coding_rules_created',
    condition_threshold: 10,
    is_negative: false,
    sort_order: 85,
  },

  // ─── Negative / Struggle ───
  {
    code: 'neg_ghost_reviewer',
    category: 'negative',
    tier: 'negative',
    name: 'Ghost Reviewer',
    description: 'Bạn đã không review commit nào trong 7 ngày. Có thể bạn cần một ít cà phê?',
    icon: 'ghost',
    xp_reward: 0,
    is_repeatable: true,
    condition_type: 'consecutive_no_review_days',
    condition_threshold: 7,
    is_negative: true,
    sort_order: 90,
  },
  {
    code: 'neg_silent_dev',
    category: 'negative',
    tier: 'negative',
    name: 'Silent Dev',
    description: 'Bạn đã không gửi daily report 5 ngày liên tiếp. Team đang lo lắng cho bạn đấy!',
    icon: 'volume-x',
    xp_reward: 0,
    is_repeatable: true,
    condition_type: 'consecutive_no_report_days',
    condition_threshold: 5,
    is_negative: true,
    sort_order: 91,
  },
  {
    code: 'neg_bug_factory',
    category: 'negative',
    tier: 'negative',
    name: 'Bug Factory',
    description: 'SpotBugs phát hiện lỗi 10 lần liên tiếp. Đã đến lúc review lại code rồi!',
    icon: 'factory',
    xp_reward: 0,
    is_repeatable: true,
    condition_type: 'consecutive_spotbugs_fails',
    condition_threshold: 10,
    is_negative: true,
    sort_order: 92,
  },
  {
    code: 'neg_file_hoarder',
    category: 'negative',
    tier: 'negative',
    name: 'File Hoarder',
    description: 'Commit một lần với hơn 100 files. Commit nhỏ hơn nhé!',
    icon: 'hard-drive',
    xp_reward: 0,
    is_repeatable: true,
    condition_type: 'commit_files_gt100_neg',
    condition_threshold: null,
    is_negative: true,
    sort_order: 93,
  },
  {
    code: 'neg_deadline_dodger',
    category: 'negative',
    tier: 'negative',
    name: 'Deadline Dodger',
    description: 'Có 3 tasks bị trễ deadline. Lần sau cố gắng nhé!',
    icon: 'calendar-x',
    xp_reward: 0,
    is_repeatable: true,
    condition_type: 'tasks_overdue_3',
    condition_threshold: null,
    is_negative: true,
    sort_order: 94,
  },
  {
    code: 'neg_big_bang',
    category: 'negative',
    tier: 'negative',
    name: 'Big Bang Committer',
    description: 'Commit một lần với hơn 200 files. Wow... chỉ biết nói WOW!',
    icon: 'zap',
    xp_reward: 0,
    is_repeatable: true,
    condition_type: 'commit_files_gt200_neg',
    condition_threshold: null,
    is_negative: true,
    sort_order: 95,
  },
  {
    code: 'neg_night_owl_7',
    category: 'negative',
    tier: 'negative',
    name: 'Extreme Night Owl',
    description: 'Commit sau 1 giờ sáng 7 lần. Sức khỏe quan trọng hơn code!',
    icon: 'moon',
    xp_reward: 0,
    is_repeatable: true,
    condition_type: 'commits_after_1am',
    condition_threshold: 7,
    is_negative: true,
    sort_order: 96,
  },
]
