/**
 * Script to remove unused translation keys from en/ja/vi translation files.
 * Reads unused keys from unused-translation-keys.txt (generated by find-unused-translation-keys.ts)
 * Excludes spotbugs.bugDescriptions - never touch it.
 * Run: pnpm tsx scripts/remove-unused-translation-keys.ts
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const LOCALES_DIR = join(ROOT, 'src/renderer/locales')
const LOCALES = ['en', 'ja', 'vi'] as const

function deleteKey(obj: Record<string, unknown>, keyPath: string): boolean {
  const parts = keyPath.split('.')
  if (parts.length === 1) {
    if (keyPath in obj) {
      delete obj[keyPath]
      return true
    }
    return false
  }
  const [head, ...rest] = parts
  const next = obj[head]
  if (next === null || typeof next !== 'object' || Array.isArray(next)) return false
  const deleted = deleteKey(next as Record<string, unknown>, rest.join('.'))
  if (deleted && Object.keys(next as object).length === 0) {
    delete obj[head]
  }
  return deleted
}

function main() {
  const unusedPath = join(ROOT, 'unused-translation-keys.txt')
  const unusedKeys = readFileSync(unusedPath, 'utf-8')
    .split('\n')
    .map((s) => s.trim())
    .filter((s) => s.length > 0 && !s.startsWith('spotbugs.bugDescriptions'))

  console.log(`Removing ${unusedKeys.length} unused keys from 3 locale files...`)

  for (const locale of LOCALES) {
    const filePath = join(LOCALES_DIR, locale, 'translation.json')
    const content = readFileSync(filePath, 'utf-8')
    const data = JSON.parse(content) as Record<string, unknown>

    let removed = 0
    for (const key of unusedKeys) {
      if (deleteKey(data, key)) removed++
    }
    console.log(`  ${locale}: removed ${removed} keys`)

    writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf-8')
  }

  console.log('Done.')
}

main()
